sonar.projectKey=devscan
sonar.projectName=DevScan
sonar.projectVersion=1.0
sonar.host.url=https://sonarcloud.io
sonar.organization=djosef0

sonar.sources=apps/api/src,apps/client/src
sonar.tests=apps/api/src/__tests__

sonar.exclusions=\
  **/node_modules/**,\
  **/.next/**,\
  **/dist/**,\
  **/build/**,\
  **/prisma/migrations/**,\
  **/*.d.ts

sonar.test.inclusions=\
  **/*.test.ts,\
  **/*.spec.ts,\
  **/__tests__/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=apps/api/tsconfig.json,apps/client/tsconfig.json

sonar.sourceEncoding=UTF-8
