FROM node:20

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY packages/typescript-config/package.json packages/typescript-config/
COPY packages/eslint-config/package.json packages/eslint-config/
COPY apps/client/package.json apps/client/

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev", "--filter", "client"]
